### ISSUE TITLE
Zooming is causing vertical scrolling of timeline area

### ISSUE THREAD

**Issue by azfoo** [TimeLineAnnotator/desktop#141]
This is only observable, of course, when the timelines are "taller" than the visible timeline area, which causes a vertical scrollbar to appear.

**Comment by azfoo** [comment]
I have an easy fix, and a proposal. It would seem that on most applications, scroll wheel alone causes vertical scrolling, with the shift key it scrolls horizontally and with control it zooms. That looks like something that can be easily implemented. Would you like to try that instead?

**Comment by FelipeDefensor** [comment]
> I have an easy fix, and a proposal. It would seem that on most applications, scroll wheel alone causes vertical scrolling, with the shift key it scrolls horizontally and with control it zooms. That looks like something that can be easily implemented. Would you like to try that instead?

Now that's something I haven't thinked about. Since the horizontal zoom was cuch a basic feature I implemented it way before I even thought about vertical scrolling.

I'm conflicted about this. On the one hand, horizontal zooming will be much more common to out users, which points to using the simpler shortcut. On the other hand, like you said, users will be used to scrolling vertically with the mouse wheel, although the great majority of analyses, I imagine, won't even have enough timeline to make vertical scrolling possible.
