### ISSUE TITLE
Suggestion: Option to annotate and save files according to discrete musical time

### ISSUE THREAD

**Issue by m-k94** [TimeLineAnnotator/desktop#233]
There are different motivations for using TiLiA, some users would want to annotate concrete audio files or videos, while others are more interested in the piece of music as it appears in a score, which just happens to find an expression in a particular recording. 

To suit these different use-cases and even build bridges between them, it could be helpful to have two different "modes" of timelines: A continuous type of timeline, based on real time in audio, and a discrete type of timeline, based on abstract musical timemarkers (beats and measures).

The former is what we already have, while the latter would only allow labels to begin and end at the points specified in the beat grid. If you drag the end of a section, it would jump from one beat to the next. It might be helpful for many people to be able to toggleswitch between these two modes while annotating, e.g. to make sure different annotations align precisely. More importantly, it could also affect on how the data is stored and used, maybe as an alternate file type:

Currently, even if you were to create an empty media time line (as #218), the data would connect all events to an arbitrary set of timecodes. So the data analyst has to write some extra code to relate these to the timecodes of the nearest beat events, specified elsewhere in the .tla file. Coming from the discrete mode, the saved file could maybe directly address a certain position on a beat grid. The annotations would, in that case, represent the structure of the musical score. A neat side effect of this could be that all kinds of different performances of that composition could be connected to the analysis: as long as the user taps out a beat layer of the appropriate length, the different sections can map onto each recording.

Would this be possible?

**Comment by johentsch** [comment]
AFAIS, the moment that symbolic music is on the table, a robust handling of musical time becomes a pressing issue. I'm convinced that you've already thought it through, @FelipeDefensor, and that some device for aligning your novel score timelines (#219) with audio is in the making. I'm just chiming in to draw your attention on two related technologies that are in practical use and for which it might therefore be worth to implement an interface (in case you're fully aware of them already, nevermind):

* the match format that is being used at JKU Linz for storing audio-score alignments on the note level
  * paper: https://doi.org/10.48550/arXiv.2206.01104
  * documentation: https://cpjku.github.io/docs/match/
  * implementation in their Partitura score parser: https://github.com/CPJKU/partitura/blob/76f18c13bfaabb32632d52701d38f322d39e955f/partitura/io/matchfile_base.py#L1010
* the MeasureMap format that Mark, the Dezrann team, and the DCML/me use in our corpora for a similar purpose (here it's about aligning the skeletons of different scores in terms of their measure counts/numbers/repeat signs etc.)
  * paper: https://dl.acm.org/doi/10.1145/3625135.3625136
  * specs: https://github.com/measure-map/specification
  * implementation: https://github.com/measure-map/pyMeasureMap

The latter will be an interesting candidate for our form project in Linz to serve as a substitute of the original music representation (score, video, beatgrid, or recording) when evaluating (only) the annotation data created with TiLiA & others. It might actually be the perfect candidate format for representing (importing/exporting) beat grids in TiLiA while accounting for all the intricacies of time signature changes, split measures, cadenzas/unmetered segments, repeated sections, deviating/wrong measure numbers, first/second endings and that awful bunch. Needless to say, all of this is relevant when considering @m-k94's suggestion.

If any of these seem interesting, I would be delighted to have a chat, and also to do the necessary work on the pyMeasureMap code.

**Comment by FelipeDefensor** [comment]
Thanks for the relevant observations, @m-k94. Adressing those two "modes" of annotating is definitely something desirable. 

As far as using data created in TiLiA for subsequent "metric-based" processing, we are nearly there. Although the .tla stores only timestamps, the output of the `export` CLI command expresses position also as metric positions. These are the attributes that are exported from a hierarchy node, for instance:

![image](https://github.com/user-attachments/assets/e5249092-f6de-4f3c-ab68-d6877640e0a3)

As you can see, we have "start" (in seconds), but also "start_beat" and "start_measure".

The output of the export command is indeed how we want to provide data for further processing, as that is decoupled from the .tla format, which we plan to change in the future.

I say we are nearly there only because `export` is currently only a CLI command, but getting that into the GUI is trivial.

With regard to annotating in a discrete timeline-space, there are some key features in that direction that I plan to implement:

1. Snapping to components: this will be a toggleable feature that will snap the dragged component to the nearest component (in whihever timeline). Snapping strongly and only to beats is equivalent to having a "discrete" timeline, as far as dragging is concerned.

2. Snap on creation: Snapping in image editing software only happens on dragging, but it will also be useful to be able to restrict the times components are created to the snap points, if the user so wishes.

3. Align existing components: This would match an existing component's time to the time of the closest component. Again, it will be useful to restrict the alignment targets to beats only, as an option.

4. Linking component's positions: there should be some way to link a component's position to another in a way that changes to the former are reflected in the latter. When we snap/align, let's say, a marker to a beat, we probably want the marker to move if the beat is dragged at a later time.

Note that even while those are not implemented, the exported JSON already informs the nearest beat/measure, which should be equivalent as far as further processing is concerned. Do you think the existing export feature is what you need? Or would the snapping/aligning features make a significant difference for your use-case?

> A neat side effect of this could be that all kinds of different performances of that composition could be connected to the analysis: as long as the user taps out a beat layer of the appropriate length, the different sections can map onto each recording.

The current worflow for mapping an anlysis into a different recording is:

1. Make a file X with the analysis of a performance A;
2. Export X to JSON;
3. Write a script that converts the JSON to one CSV file per timeline;
4. Make a new file Y and tap beats to recording B;
5. Import the CSVs from (3) into Y.

Ideally, we would have an option to export a file directly to CSVs, merging steps (2) and (3), but writing the script for (3) should be easy.

**Comment by FelipeDefensor** [comment]
> AFAIS, the moment that symbolic music is on the table, a robust handling of musical time becomes a pressing issue. I'm convinced that you've already thought it through, @FelipeDefensor, and that some device for aligning your novel score timelines (#219) with audio is in the making.

Thanks for highlighting this. I believe what we already have in place goes a long way when it comes to aligning a specific score to a specific performance. The user loads an audio file, insert the beats, adjust the measure numbers to match those on the score, import the score and TiLiA does the aligning.

Things get more complex when we are dealing with multiple recordings/scores, and there is where I think both the match format and MeasureMap can help a lot. Also, I admit I haven't given much thought to that yet. I imagine we can use MeasureMap to convert analysis from one performance/score to the other, given existing beat timelines. That's not something I would imagine being a part of TiLiA itself, though, but something that's part of a pipeline that uses the TiLiA CLI, for instance.

I'm up for a chat to know more about your specific use-case, if you are at the point where you know it in any detail. That would help me have a clearer picture of all this.

**Comment by FelipeDefensor** [comment]
Glad to hear that! Yes, CLI export and the features mentioned in the issues in the past weeks will all be available in the next release. If you want to try them right now, most are already merged into the dev branch (including CLI export).

**Comment by MarkGotham** [comment]
Thanks all.

An important topic to be sure and great to see "many heads" combining to address it!

In addition to the refs above, some more from the Müller group (Audio labs, Erlangen):
- Verena Thomas, Christian Fremerey, Meinard Müller, and Michael Clausen: Linking Sheet Music and Audio — Challenges and New Approaches. Dagstuhl 2012.
- Christian Fremerey, Meinard Müller, and Michael Clausen: Handling Repeats and Jumps in Score-Performance Synchronization. ISMIR 2010
- Müller's FMP textbook addresses unfolding repeats.

**Comment by johentsch** [comment]
Hi everyone, here's a draft for a protocol from yesterday's meeting: https://hackmd.io/@johentsch/timelines @azfoo, @FelipeDefensor, @m-k94 and @manoskary, please feel free to log into HackMD to modify/complete it.

**Comment by FelipeDefensor** [comment]
Thanks, Johannes. I added the bit about using beat numbers in out CSV imports that Anne suggested.

**Comment by FelipeDefensor** [comment]
A little delayed, but e9ff87d7543dde4d86f254b77bb8ef47c5255bb1 adds the export command to the GUI.
